name: "Continuous Deployment"
on:
    workflow_run:
        workflows: ["Continous integration"]
        types:
            - completed
jobs:
    fetch_and_deploy :
        runs-on: self-hosted
        steps:
            - name: "Install kubectl"
              uses: azure/setup-kubectl@v3
              with: 
                version: "v1.19.3"
                id: "install-kubectl"
            
            - name: "Setup AWS Credentials"
              uses: aws-actions/configure-aws-credentials@v4
              with: 
                aws-region: "us-east-1"
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                aws-secret-access-key:  ${{ secrets.AWS_SECRET_KEY }}

            - name: "Connect to the cluster"
              run: |
                aws eks update-kubeconfig --name <name>

            - name: "Install Helm"
              uses: azure/setup-helm@v4.2.0
              id: "install-helm"

            - name: "Use helm to install our charts"
              run: |
                helm upgrade --install <name> <name -f <helm name>/values.yaml> --set image.tag=${{ env.VERSION_NUMBER}} --set replicaCount=2 
            
            - name: "Announce the latest version of the deployment"
              uses: dawidd6/action-send-mail@v3
              with:
                        username: <email>
                        password: ${{ secrets.EMAIL_PASSWORD }}
                        server_address: smtp.gmail.com
                        server_port: 465
                        secure: true
                        subject: "New Docker Image Version for bloggin Web App - app-deployment"
                        to: <recipient emails>
                        from: <name>, <email>
                        body: "New image build:<name>/<name>:${{ env.VERSION_NUMBER }}"
