name: Continous integration
on: 
  push:
    branches:
      - master
jobs: 
  app-deployment:
    runs-on: self-hosted
    steps: 
      - name: "first run job"
        run: |
          echo "--- welcome to CI-Deployment: ---"
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Create version number"
        run: |
          echo "VERSION_NUMBER=${RANDOM}" >> $GITHUB_ENV
  
      -  name: "Build a Docker image from the repo"
         run: |
            sudo docker build -t abatan/pixer:${{ env.VERSION_NUMBER }} .

      - name: "Log into Docker Hub"
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: "Push to Docker Hub"
        run: |
          sudo docker push abatan/pixer:${{ env.VERSION_NUMBER }}
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'abatan/pixer:${{ env.VERSION_NUMBER }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
        
      - name: Upload Trivy scan results
        uses: actions/upload-artifact@v3
        with:
            name: trivy-scan-results
            path: trivy-image.txt
        

      