name: Continous integration
on: 
  push:
    branches:
      - master
jobs: 
  app-deployment:
    runs-on: self-hosted
    steps: 
      - name: "first run job"
        run: |
          echo "--- welcome to app-deployment: ---"
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Create version number"
        run: |
          echo "VERSION_NUMBER=${RANDOM}" >> $GITHUB_ENV
  
      -  name: "Build a Docker image from the repo"
         run: |
            docker built -t <name>/<name>:${{ env.VERSION_NUMBER }} .

      - name: "Log into Docker Hub"
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: "Push to Docker Hub"
        run: |
          docker push <name>/<name>:${{ env.VERSION_NUMBER }}

      